// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtmolxwkfzyeixducsdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0bW9seHdrZnp5ZWl4ZHVjc2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTEzNzAsImV4cCI6MjA1OTkyNzM3MH0.u2L6TjLVHe2Q8C4MIPKOBNix8j7s6K6lwLDT2tv4SUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);